version: 2

build:
  image: latest

sphinx:
  configuration: docs/conf.py

formats: all

python:
  version: 3.8
  install:
  - method: pip
    path: .
    extra_requirements:
    - requirements: docs/requirements.txt